### PR TITLE
Detect issue related to transmission-common and reinstall it if needed

### PR DESCRIPTION
**Pull request by alexAubin**
## Problem

 c.f. https://github.com/YunoHost-Apps/transmission_ynh/issues/44 which is a fucking crazy issue where `transmission-daemon` and `transmission-common` were installed, but somehow the transmission user was not there, nor the `/usr/share/transmission` files :sweat: 

I think this was at least the 3rd time I saw this issue happen ...

## Solution

Was finally able to fix the issue by running `apt install transmission-common --reinstall` :sweat: 

Made this YOLO PR, not really tested...

## PR Status
- [X] Code finished.
- [ ] Tested with Package_check.
- [ ] Fix or enhancement tested.
- [ ] Upgrade from last version tested.
- [ ] Can be reviewed and tested.

## Validation
---
*Minor decision*
- **Upgrade previous version** : 
- [x] **Code review** : Kay0u
- [x] **Approval (LGTM)** : Kay0u
- [x] **Approval (LGTM)** : Maniack C
- **CI succeeded** : [Build Status](https://ci-apps-dev.yunohost.org/jenkins/job/transmission_ynh%20PR52/)  
When the PR is marked as ready to merge, you have to wait for 3 days before really merging it.

### CODE REVIEW

**Comment by maniackcrudelis** [comment]
Do you think it could be related to how apt handles dependencies ?
Maybe we could add those packages as a clear dependencies in `ynh_install_app_dependencies` ?

**Comment by alexAubin** [comment]
I asked the user to run `dpkg --list | grep transmission` and `transmission-common` *was* installed (since it's a dependency of transmission-daemon) ... but somehow the files that `transmission-common` was supposed to put weren't there -.-

**Comment by maniackcrudelis** [comment]
I don't know how this is even possible...
As your code is pretty clean, I guess we can merge that.
I will commit tough to add those packages as clear dependencies.

**Comment by maniackcrudelis** [comment]
Let's merge in 3 days then.

**Pull request merged**
