### PR TITLE
Add rpc-host-whitelist

### PR DESCRIPTION
**Pull request by maniackcrudelis**
## Problem
- *Fix https://github.com/YunoHost-Apps/transmission_ynh/issues/47*
I don't reproduce the error though...

## Solution
- *Add the missing options*

## PR Status
- [x] Code finished.
- [ ] Tested with Package_check.
- [ ] Fix or enhancement tested.
- [ ] Upgrade from last version tested.
- [x] Can be reviewed and tested.

## Validation
---
*Minor decision*
- **Upgrade previous version** : 
- [x] **Code review** : JimboJoe
- [x] **Approval (LGTM)** : JimboJoe
- [ ] **Approval (LGTM)** : 
- **CI succeeded** : 
[Build Status/badge/icon)](https://ci-apps-dev.yunohost.org/jenkins/job/transmission_ynh%20add-rpc-host-whitelist%20(Official)/)  
When the PR is marked as ready to merge, you have to wait for 3 days before really merging it.

### CODE REVIEW

**Comment by JimboJoe** [comment]
Upgrade from previous version failing in the CI due to missing `setfacl` command...

**Comment by maniackcrudelis** [comment]
Ok, so we should move to this commit, https://github.com/YunoHost-Apps/transmission_ynh/commit/7d887f6bc1e29ce94de703517d5302580cbb8a7e, for this test

**Comment by alexAubin** [comment]
Bumpity bump ? Sounds like this is easy to merge :s

**Comment by alexAubin** [comment]
Bumpity bump ? Sounds like this is easy to merge :s

**Comment by maniackcrudelis** [comment]
The failed upgrade will be fix by another PR, https://github.com/YunoHost-Apps/transmission_ynh/pull/50.
Meanwhile, this PR can use a last approval.

**Comment by JimboJoe** [comment]
Will be merged in 3 days.

**Pull request merged**
