### PR TITLE
Add change_url and package_linter fixes

### PR DESCRIPTION
**Pull request by MCMic**
Hello,

This PR adds a change_url script, inspired by the one for etherpad, the only thing specific to transmission is the modifying of the settings file. I did not test this script.

The PR also contains some fixes spotted by package_linter, and comment changes to match example_ynh closer.

Not sure what to do about «! [YEP-2.1]transmission-daemon service may not exist», does that mean that transmission-daemon should not be stated in services in the manifest?

---

## Problem
- *Description of why you made this PR*

## Solution
- *And how you fix that*

## PR Status
- [ ] Code finished.
- [ ] Tested with Package_check.
- [ ] Fix or enhancement tested.
- [ ] Upgrade from last version tested.
- [ ] Can be reviewed and tested.

## Validation
---
*Minor decision*
- **Upgrade previous version** : 
- [ ] **Code review** : 
- [ ] **Approval (LGTM)** : 
- [ ] **Approval (LGTM)** : 
- **CI succeeded** : [Build Status/badge/icon)](https://ci-apps-dev.yunohost.org/jenkins/job/transmission_ynh%20PR43%20(Official_fork)/)  
When the PR is marked as ready to merge, you have to wait for 3 days before really merging it.

### CODE REVIEW

**Comment by maniackcrudelis** [comment]
The _common.sh file is "common" to all scripts inside the app only.
But actually yes, etherpad uses [Experimental helpers](https://github.com/YunoHost-Apps/Experimental_helpers/blob/master/ynh_check_starting/ynh_check_starting) which are not available unless you add them in the _common.sh.

Anyway, here, you can remove this function `ynh_clean_check_starting` which is related to this other one `ynh_check_starting` that you don't use in your script.
This helper is used by Etherpad to be sure that etherpad is fully started before ending the script. This is not needed by transmission.

But, nevertheless, the problem is not about this missing helper, if you have a closer look to the CI log, nginx failed to reload. And that the problem here.
And because fixing the nginx file can be difficult in this script, I would encourage you to have a look to the new way to writing change_url script.
[Here an example with wallabag2](https://github.com/YunoHost-Apps/wallabag2_ynh/blob/enh_simplify_change_url/scripts/change_url) which uses the original nginx conf file in conf/nginx.conf

If you need or would like any help on this PR, don't hesitate to ask. We can help you to go forward on this.
By the way, thanks for your highly appreciate contribution.

**Comment by JimboJoe** [comment]
Thanks for your contribution!
As you can see in the badge in your initial PR, the build is failing.
You'll find [here](https://ci-apps-dev.yunohost.org/jenkins/job/transmission_ynh%20PR43%20(Official_fork)/lastBuild/consoleFull) (or by clicking on the badge) the execution log.
The change_url is failing for (at least) 2 reasons:
- you must include (at least for now) the `ynh_delete_file_checksum` helper in `_common.sh`
- the nginx configuration makes nginx startup failing.

Do you possibly have testing means (package_check, VM,...) to understand why?

Thanks!

**Comment by MCMic** [comment]
Hey, yeah I found the link to the CI.
Regarding package_check, it’s not a 100% clear to me if:

- I need to set up stuff before running it
- I can run in on ArchLinux or it relies on Debian
- I can run it on my personal computer without risk or it will left over stuff

Also I need a lot of free disk space to run that no?

Regarding the CI, why does it say: «Warning: yunohost.app app_checkurl - [1083.1] Packagers /! 'app checkurl' is deprecated ! Please use 'app register-url' instead !»
I do not call any checkurl command in my script.

I will add the missing ynh_delete_file_checksum.

Shouldn’t there be a generic helper to change url&path instead of copy/pasting in each app? The most part is generic the only thing specific to transmission is the config file path replacement.

**Comment by JimboJoe** [comment]
> Hey, yeah I found the link to the CI.
> Regarding package_check, it’s not a 100% clear to me if:
> 
>     I need to set up stuff before running it
Yes, you need to install it. You also have the option to rely on our [testing CI](https://forum.yunohost.org/t/proposition-for-a-new-non-official-ci/3595). I've never tested it, though :innocent: 

>     I can run in on ArchLinux or it relies on Debian
I think it's only been tested on Debian. I'm using it myself inside my YunoHost development VM.
>     I can run it on my personal computer without risk or it will left over stuff
No problem if you use it inside a VM. Otherwise I can't really say...
> 
> Also I need a lot of free disk space to run that no?

It's using about 10Gb on my development VM at the moment.

> 
> Regarding the CI, why does it say: «Warning: yunohost.app app_checkurl - [1083.1] Packagers /! 'app checkurl' is deprecated ! Please use 'app register-url' instead !»
> I do not call any checkurl command in my script.

This warning is due to a remaining use of checkurl inside YunoHost moulinette for change-url feature. There's nothing you can do in your app.
> 
> I will add the missing ynh_delete_file_checksum.

Thanks!
> 
> Shouldn’t there be a generic helper to change url&path instead of copy/pasting in each app? The most part is generic the only thing specific to transmission is the config file path replacement.

That's an interesting idea! As this helper hasn't been widely used yet, we still don't have much experience in what can be communalized.

**Comment by MCMic** [comment]
I have really no idea why the URl change keep failing on the jenkins, there is not much information, is there any way to get the error returned by the script if any?

On my yunohost I changed the transmission domain by hand (not with this script) and it went smoothly with no problem. I did not try to change the path as I did not need that.

**Comment by JimboJoe** [comment]
If you're using package_check, you can launch it with the `--interrupt` option so that it pauses after each test, and you can log into the container with `ssh -t pchecker_lxc` so you can look into log files (and here potentially the nginx log file).

**Comment by alexAubin** [comment]
Bumpz :s

**Comment by kay0u** [comment]
I close this RP because the same work has been done here: #60 
Anyway, thank you for you contribution, and feel free to reopen it again if you think this PR is still relevant

**Pull request closed without merging**
