### PR TITLE
Testing

### PR DESCRIPTION
**Pull request by JimboJoe**
## Problem
- *Scripts are a little bit out of date*

## Solution
- *Update of the scripts and helpers*

## PR Status
Work finished. Package_check, basic tests and upgrade from last version OK.  
Could be reviewed and tested.

## Validation
*Medium decision*
- [x] **Complete test** : From testing https://forum.yunohost.org/t/testing-branches-for-apps/3470/16
- [x] **Upgrade previous version** : JimboJoe from https://github.com/YunoHost-Apps/transmission_ynh/pull/31
- [x] **Code review** : frju365 from https://github.com/YunoHost-Apps/transmission_ynh/pull/31
- [ ] **Code review** : 
- [x] **Approval (LGTM)** : frju365 from https://github.com/YunoHost-Apps/transmission_ynh/pull/31
- [x] **Approval (LGTM)** : JimboJoe from https://github.com/YunoHost-Apps/transmission_ynh/pull/31
- [ ] **Approval (LGTM)** : 
- [x] **CI succeeded** : JimboJoe from https://github.com/YunoHost-Apps/transmission_ynh/pull/31
- [x] **CI succeeded** : [Build Status/badge/icon)](https://ci-apps-dev.yunohost.org/jenkins/job/transmission_ynh%20testing%20(Official)/)  
One public package check log is enough instead of two checks.  
When the PR is mark as ready to merge, you have to wait for 7 days before really merge it.

### CODE REVIEW

**Comment by alexAubin** [comment]
Hellow,

thanks for the awesome work !

I dunno if that's just me, but after upgrading (?), Transmission was unable to add new files in the completed location because /home/yunohost.transmission was missing 'x' permission for owner :  

```
drw-rwxr-x+  3 debian-transmission www-data 1024 Nov  5 22:51 yunohost.transmission
```

**Comment by maniackcrudelis** [comment]
> I dunno if that's just me, but after upgrading (?), Transmission was unable to add new files in the completed location because /home/yunohost.transmission was missing 'x' permission for owner

Indeed, from the current stable to testing there an error.
I'm trying to find where.

**Comment by maniackcrudelis** [comment]
Ok just here... https://github.com/YunoHost-Apps/transmission_ynh/blob/master/scripts/upgrade#L78

**Comment by maniackcrudelis** [comment]
I need to check the integration with multimedia directory.
I do that as soon as possible.

**Comment by maniackcrudelis** [comment]
> I need to check the integration with multimedia directory.
I do that as soon as possible.

Done, it's ok.

**Comment by maniackcrudelis** [comment]
So, let's merge it all !!! (In 3 days...)

**Pull request merged**
